### ISSUE TITLE
Release Question

### ISSUE THREAD

**Issue by jklaus** [SEEK-Jobs/pact-net#106] opened 2017-08-15 13:35 UTC
Sorry for asking in this manner, please let me know if there is a better way to communicate and feel free to remove this issue.

I'm leveraging your library in .Net Core targetting 461 and was curious how soon we might see the Match functionality in a formal release.  I can hold out for a little while but before going to prime time I'll need to get off the beta release.  Also - thanks!

**Comment by neilcampbell** [comment] 2017-08-15 23:10
@jklaus No problems. The big piece outstanding before it becomes a non-beta release is cross platform support, as that slightly changes the way the package is installed. I'm hoping to have that sorted by the end of the weekend, so if all goes to plan we should be good by mid next week or something like that.

**Comment by jklaus** [comment] 2017-08-16 11:51
Out of curiosity have you tested this with VS15 .NET core projects
targeting 461?  No matter where I execute the download script I'm getting a
file not found.  Or is this part of the cross platform support you
mentioned?  I'm having no issues in similar VS17 projects.

**Comment by neilcampbell** [comment] 2017-08-16 22:46
@jklaus What do you mean download script? Are you running the samples or are you running your own project? If it's your own project you do not need to run any download scripts. The PactNet project is a VS2017 only solution.

The samples only need to do this, as we take a project dependency on PactNet rather than a nuget dependency. The ruby core is currently packaged into the PactNet nuget package. This is also being changed with the cross platform support work, as we can install the OS specific nuget package into the samples.

It should all work fine if you are creating your own VS15 .NET core projects targeting 461 and installing the latest beta nuget package. It would be awesome though if you could test to make sure that works ok on your end.

**Comment by jklaus** [comment] 2017-08-17 12:54
This was occurring in my own VS15 project.  I nugot the 2.0.7beta release
and refactored tests accordingly.. header collection went from <string,
string> to <string, object>.  When I tried to run the tests I'd get an
exception related to not being able to find a file.  No details on what
file it couldn't find.  After that I took a look at your sample projects
and saw in one of your pact classes you were checking for a file and if it
wasn't found you threw an exception telling the user to execute
~\Build\DownloadBlahBlahBlah.  As an attempt to solve my missing file issue
I tried running that download script.  All this said while I was fighting
that a coworker had unknowingly migrated the project to VS17 in a separate
branch so I just merged his changes into mine and we're good to go in
VS17.  Not sure why its not finding the file in VS15, perhaps it has more
to do with the older version of nuget?

**Comment by jklaus** [comment] 2017-08-17 14:53
I even tried manually copying the pact directory from a working VS17 project to the non-functional VS15 project.  As I say that I wonder if the pact directory didn't need to be added as content to the project.json

**Comment by neilcampbell** [comment] 2017-08-18 02:40
Thanks for the additional details, will try reproduce on the weekend after I am finished with the cross platform stuff. If you could send a sample repo that reproduces the issue, that would be amazing.

**Comment by neilcampbell** [comment] 2017-08-21 06:39
@jklaus The cross platform work has now been merged into master, so the samples will look a little closer to what I expect a standard user would do. Please not this is a VS2017 only solution, but you shouldn't have any issues installing PactNet nuget package in a VS2015 solution.

Are you able to try again with the latest nuget package?

**Comment by jklaus** [comment] 2017-08-21 14:53
@neilcampbell Sorry I forgot I was to be on dad duty Sunday so I didn't get around to creating the VS15 test project.  I'll try to get back to this today.

**Comment by davidchipping** [comment] 2017-08-31 08:58
Sorry to jump on the back of this issue (if there is a better way of asking please let me know) but it seemed related. I was wondering if there was a rough ETA for the RC 2.0 release?

**Comment by neilcampbell** [comment] 2017-08-31 09:08
@davidchipping No worries mate, this is fine.

I'm ready to release it now.
Have you installed the latest beta and are happy with everything?

I was just planning on waiting for confirmation from @jklaus that the issue is sorted, but I may just end up dropping it if everyone is happy with the beta.

**Comment by davidchipping** [comment] 2017-09-05 15:38
> Have you installed the latest beta and are happy with everything?

At the moment we're happy with it :+1:

**Comment by neilcampbell** [comment] 2017-09-06 08:17
The first official v2 spec release has been created (2.0.17).

To install use either:
- PactNet.Windows (was previously PactNet-Windows)
- PactNet.OSX (was previously PactNet-OSX)
- PactNet.Linux.x86 (was previously PactNet-Linux-x86)
- PactNet.Linux.x64 (was previously PactNet-Linux-x64)

**Closed** 2017-09-06 08:17 UTC
Labels: question
